In [1]:
!pwd

/Users/jackhousego/code/hughharford/smr/smr/notebooks

In [4]:
import pandas as pd

In [2]:
null = None

In [46]:
js = {
  "0": {
    "0": null,
    "1": null,
    "2": null,
    "3": null,
    "4": null,
    "5": null,
    "6": null,
    "7": null,
    "8": null,
    "9": null,
    "10": null,
    "11": null,
    "12": null,
    "13": null,
    "14": null,
    "15": null,
    "16": null,
    "17": null,
    "18": null,
    "19": null,
    "20": null,
    "21": null,
    "22": null,
    "23": null,
    "24": null,
    "25": null,
    "26": null,
    "27": null,
    "28": null,
    "29": null,
    "30": null,
    "31": null,
    "32": null,
    "33": null,
    "34": null,
    "35": null,
    "36": null,
    "37": null,
    "38": null,
    "39": null,
    "40": null,
    "41": null,
    "42": null,
    "43": null,
    "44": null,
    "45": null,
    "46": null,
    "47": null,
    "48": null,
    "49": null,
    "50": null,
    "51": null,
    "52": null,
    "53": null,
    "54": null,
    "55": null,
    "56": null,
    "57": null,
    "58": null,
    "59": null,
    "60": null,
    "61": null,
    "62": null,
    "63": null,
    "64": null,
    "65": null,
    "66": null,
    "67": null,
    "68": null,
    "69": null,
    "70": null,
    "71": null,
    "72": null,
    "73": null,
    "74": null,
    "75": null,
    "76": null,
    "77": null,
    "78": null,
    "79": null,
    "80": null,
    "81": null,
    "82": null,
    "83": null,
    "84": null,
    "85": null,
    "86": null
  },
  "1": {
    "0": "SE23 3YL",
    "1": "G3 xxx",
    "2": "latt long",
    "3": "latt long",
    "4": "SE23 3YL",
    "5": "G3 xxx",
    "6": "latt long",
    "7": "latt long",
    "8": "SE23 3YL",
    "9": "G3 xxx",
    "10": "latt long",
    "11": "latt long",
    "12": "SE23 3YL",
    "13": "G3 xxx",
    "14": "latt long",
    "15": "latt long",
    "16": "SE23 3YL",
    "17": "G3 xxx",
    "18": "latt long",
    "19": "latt long",
    "20": "SE23 3YL",
    "21": "G3 xxx",
    "22": "latt long",
    "23": "SE23 3YL",
    "24": "G3 xxx",
    "25": "latt long",
    "26": "SE23 3YL",
    "27": "G3 xxx",
    "28": "latt long",
    "29": "SE23 3YL",
    "30": "G3 xxx",
    "31": "latt long",
    "32": "SE23 3YL",
    "33": "G3 xxx",
    "34": "latt long",
    "35": "SE23 3YL",
    "36": "G3 xxx",
    "37": "latt long",
    "38": "SE23 3YL",
    "39": "G3 xxx",
    "40": "latt long",
    "41": "SE23 3YL",
    "42": "G3 xxx",
    "43": "latt long",
    "44": "SE23 3YL",
    "45": "SE23 3YL",
    "46": "SE23 3YL",
    "47": "SE23 3YL",
    "48": "SE23 3YL",
    "49": "SE23 3YL",
    "50": "SE23 3YL",
    "51": "SE23 3YL",
    "52": "SE23 3YL",
    "53": "SE23 3YL",
    "54": "SE23 3YL",
    "55": "SE23 3YL",
    "56": "SE23 3YL",
    "57": "SE23 3YL",
    "58": "SE23 3YL",
    "59": "SE23 3YL",
    "60": "SE23 3YL",
    "61": "SE23 3YL",
    "62": "SE23 3YL",
    "63": "SE23 3YL",
    "64": "SE23 3YL",
    "65": "SE23 3YL",
    "66": "SE23 3YL",
    "67": "SE23 3YL",
    "68": "SE23 3YL",
    "69": "SE23 3YL",
    "70": "SE23 3YL",
    "71": "SE23 3YL",
    "72": "SE23 3YL",
    "73": "SE23 3YL",
    "74": "SE23 3YL",
    "75": "SE23 3YL",
    "76": "SE23 3YL",
    "77": "SE23 3YL",
    "78": "SE23 3YL",
    "79": "SE23 3YL",
    "80": "SE23 3YL",
    "81": "SE23 3YL",
    "82": "SE23 3YL",
    "83": "SE23 3YL",
    "84": "SE23 3YL",
    "85": "SE23 3YL",
    "86": "SE23 3YL"
  },
  "2": {
    "0": "SE23 3YL",
    "1": "G3 xxx",
    "2": "SE23 3YL",
    "3": "empty",
    "4": "SE23 3YL",
    "5": "G3 xxx",
    "6": "SE23 3YL",
    "7": "empty",
    "8": "SE23 3YL",
    "9": "G3 xxx",
    "10": "SE23 3YL",
    "11": "empty",
    "12": "SE23 3YL",
    "13": "G3 xxx",
    "14": "SE23 3YL",
    "15": "empty",
    "16": "SE23 3YL",
    "17": "G3 xxx",
    "18": "SE23 3YL",
    "19": "empty",
    "20": "SE23 3YL",
    "21": "G3 xxx",
    "22": "SE23 3YL",
    "23": "SE23 3YL",
    "24": "G3 xxx",
    "25": "SE23 3YL",
    "26": "SE23 3YL",
    "27": "G3 xxx",
    "28": "SE23 3YL",
    "29": "SE23 3YL",
    "30": "G3 xxx",
    "31": "SE23 3YL",
    "32": "SE23 3YL",
    "33": "G3 xxx",
    "34": "SE23 3YL",
    "35": "SE23 3YL",
    "36": "G3 xxx",
    "37": "SE23 3YL",
    "38": "SE23 3YL",
    "39": "G3 xxx",
    "40": "SE23 3YL",
    "41": "SE23 3YL",
    "42": "G3 xxx",
    "43": "SE23 3YL",
    "44": "SE23 3YL",
    "45": "SE23 3YL",
    "46": "SE23 3YL",
    "47": "SE23 3YL",
    "48": "SE23 3YL",
    "49": "SE23 3YL",
    "50": "SE23 3YL",
    "51": "SE23 3YL",
    "52": "SE23 3YL",
    "53": "SE23 3YL",
    "54": "SE23 3YL",
    "55": "SE23 3YL",
    "56": "SE23 3YL",
    "57": "SE23 3YL",
    "58": "SE23 3YL",
    "59": "SE23 3YL",
    "60": "SE23 3YL",
    "61": "SE23 3YL",
    "62": "SE23 3YL",
    "63": "SE23 3YL",
    "64": "SE23 3YL",
    "65": "SE23 3YL",
    "66": "SE23 3YL",
    "67": "SE23 3YL",
    "68": "SE23 3YL",
    "69": "SE23 3YL",
    "70": "SE23 3YL",
    "71": "SE23 3YL",
    "72": "SE23 3YL",
    "73": "SE23 3YL",
    "74": "SE23 3YL",
    "75": "SE23 3YL",
    "76": "SE23 3YL",
    "77": "SE23 3YL",
    "78": "SE23 3YL",
    "79": "SE23 3YL",
    "80": "SE23 3YL",
    "81": "SE23 3YL",
    "82": "SE23 3YL",
    "83": "SE23 3YL",
    "84": "SE23 3YL",
    "85": "SE23 3YL",
    "86": "SE23 3YL"
  },
  "3": {
    "0": 45,
    "1": 1001,
    "2": 23,
    "3": 1,
    "4": 45,
    "5": 1001,
    "6": 23,
    "7": 1,
    "8": 45,
    "9": 1001,
    "10": 23,
    "11": 1,
    "12": 45,
    "13": 1001,
    "14": 23,
    "15": 1,
    "16": 45,
    "17": 1001,
    "18": 23,
    "19": 1,
    "20": 45,
    "21": 1001,
    "22": 23,
    "23": 45,
    "24": 1001,
    "25": 23,
    "26": 45,
    "27": 1001,
    "28": 23,
    "29": 45,
    "30": 1001,
    "31": 23,
    "32": 45,
    "33": 1001,
    "34": 23,
    "35": 45,
    "36": 1001,
    "37": 23,
    "38": 45,
    "39": 1001,
    "40": 23,
    "41": 45,
    "42": 1001,
    "43": 23,
    "44": 1,
    "45": 1,
    "46": 1,
    "47": 1,
    "48": 1,
    "49": 1,
    "50": 1,
    "51": 3,
    "52": 1,
    "53": 1,
    "54": 1,
    "55": 1,
    "56": 1,
    "57": 1,
    "58": 1,
    "59": 1,
    "60": 1,
    "61": 1,
    "62": 1,
    "63": 1,
    "64": 1,
    "65": 1,
    "66": 1,
    "67": 1,
    "68": 1,
    "69": 1,
    "70": 1,
    "71": 1,
    "72": 1,
    "73": 1,
    "74": 1,
    "75": 1,
    "76": 1,
    "77": 1,
    "78": 1,
    "79": 1,
    "80": 1,
    "81": 1,
    "82": 64,
    "83": 1,
    "84": 66,
    "85": 1,
    "86": 68
  },
  "4": {
    "0": 0,
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": 0,
    "8": 0,
    "9": 0,
    "10": 0,
    "11": 0,
    "12": 0,
    "13": 0,
    "14": 0,
    "15": 0,
    "16": 0,
    "17": 0,
    "18": 0,
    "19": 0,
    "20": 0,
    "21": 0,
    "22": 0,
    "23": 0,
    "24": 0,
    "25": 0,
    "26": 0,
    "27": 0,
    "28": 0,
    "29": 0,
    "30": 0,
    "31": 0,
    "32": 0,
    "33": 0,
    "34": 0,
    "35": 0,
    "36": 0,
    "37": 0,
    "38": 0,
    "39": 0,
    "40": 0,
    "41": 0,
    "42": 0,
    "43": 0,
    "44": 722,
    "45": 722,
    "46": 722,
    "47": 722,
    "48": 722,
    "49": 722,
    "50": 722,
    "51": 722,
    "52": 722,
    "53": 722,
    "54": 722,
    "55": 722,
    "56": 722,
    "57": 722,
    "58": 722,
    "59": 722,
    "60": 722,
    "61": 722,
    "62": 722,
    "63": 722,
    "64": 722,
    "65": 722,
    "66": 722,
    "67": 722,
    "68": 722,
    "69": 722,
    "70": 722,
    "71": 722,
    "72": 722,
    "73": 722,
    "74": 722,
    "75": 722,
    "76": 722,
    "77": 722,
    "78": 722,
    "79": 722,
    "80": 722,
    "81": 722,
    "82": 722,
    "83": 722,
    "84": 722,
    "85": 722,
    "86": 722
  },
  "5": {
    "0": 0,
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": 0,
    "8": 0,
    "9": 0,
    "10": 0,
    "11": 0,
    "12": 0,
    "13": 0,
    "14": 0,
    "15": 0,
    "16": 0,
    "17": 0,
    "18": 0,
    "19": 0,
    "20": 0,
    "21": 0,
    "22": 0,
    "23": 0,
    "24": 0,
    "25": 0,
    "26": 0,
    "27": 0,
    "28": 0,
    "29": 0,
    "30": 0,
    "31": 0,
    "32": 0,
    "33": 0,
    "34": 0,
    "35": 0,
    "36": 0,
    "37": 0,
    "38": 0,
    "39": 0,
    "40": 0,
    "41": 0,
    "42": 0,
    "43": 0,
    "44": 17,
    "45": 17,
    "46": 17,
    "47": 17,
    "48": 17,
    "49": 17,
    "50": 17,
    "51": 17,
    "52": 17,
    "53": 17,
    "54": 17,
    "55": 17,
    "56": 17,
    "57": 17,
    "58": 17,
    "59": 17,
    "60": 17,
    "61": 17,
    "62": 17,
    "63": 17,
    "64": 17,
    "65": 17,
    "66": 17,
    "67": 17,
    "68": 17,
    "69": 17,
    "70": 17,
    "71": 17,
    "72": 17,
    "73": 17,
    "74": 17,
    "75": 17,
    "76": 17,
    "77": 17,
    "78": 17,
    "79": 17,
    "80": 17,
    "81": 17,
    "82": 17,
    "83": 17,
    "84": 17,
    "85": 17,
    "86": 17
  },
  "6": {
    "0": 0,
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": 0,
    "8": 0,
    "9": 0,
    "10": 0,
    "11": 0,
    "12": 0,
    "13": 0,
    "14": 0,
    "15": 0,
    "16": 0,
    "17": 0,
    "18": 0,
    "19": 0,
    "20": 0,
    "21": 0,
    "22": 0,
    "23": 0,
    "24": 0,
    "25": 0,
    "26": 0,
    "27": 0,
    "28": 0,
    "29": 0,
    "30": 0,
    "31": 0,
    "32": 0,
    "33": 0,
    "34": 0,
    "35": 0,
    "36": 0,
    "37": 0,
    "38": 0,
    "39": 0,
    "40": 0,
    "41": 0,
    "42": 0,
    "43": 0,
    "44": 5,
    "45": 5,
    "46": 5,
    "47": 5,
    "48": 5,
    "49": 5,
    "50": 5,
    "51": 5,
    "52": 5,
    "53": 5,
    "54": 5,
    "55": 5,
    "56": 5,
    "57": 5,
    "58": 5,
    "59": 5,
    "60": 5,
    "61": 5,
    "62": 5,
    "63": 5,
    "64": 5,
    "65": 5,
    "66": 5,
    "67": 5,
    "68": 5,
    "69": 5,
    "70": 5,
    "71": 5,
    "72": 5,
    "73": 5,
    "74": 5,
    "75": 5,
    "76": 5,
    "77": 5,
    "78": 5,
    "79": 5,
    "80": 5,
    "81": 5,
    "82": 5,
    "83": 5,
    "84": 5,
    "85": 5,
    "86": 5
  },
  "7": {
    "0": 0,
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": 0,
    "8": 0,
    "9": 0,
    "10": 0,
    "11": 0,
    "12": 0,
    "13": 0,
    "14": 0,
    "15": 0,
    "16": 0,
    "17": 0,
    "18": 0,
    "19": 0,
    "20": 0,
    "21": 0,
    "22": 0,
    "23": 0,
    "24": 0,
    "25": 0,
    "26": 0,
    "27": 0,
    "28": 0,
    "29": 0,
    "30": 0,
    "31": 0,
    "32": 0,
    "33": 0,
    "34": 0,
    "35": 0,
    "36": 0,
    "37": 0,
    "38": 0,
    "39": 0,
    "40": 0,
    "41": 0,
    "42": 0,
    "43": 0,
    "44": 723,
    "45": 723,
    "46": 723,
    "47": 723,
    "48": 723,
    "49": 723,
    "50": 723,
    "51": 723,
    "52": 723,
    "53": 723,
    "54": 723,
    "55": 723,
    "56": 723,
    "57": 723,
    "58": 723,
    "59": 723,
    "60": 723,
    "61": 723,
    "62": 723,
    "63": 723,
    "64": 723,
    "65": 723,
    "66": 723,
    "67": 723,
    "68": 723,
    "69": 723,
    "70": 723,
    "71": 723,
    "72": 723,
    "73": 723,
    "74": 723,
    "75": 723,
    "76": 723,
    "77": 723,
    "78": 723,
    "79": 723,
    "80": 723,
    "81": 723,
    "82": 723,
    "83": 723,
    "84": 723,
    "85": 723,
    "86": 723
  },
  "8": {
    "0": 0,
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": 0,
    "8": 0,
    "9": 0,
    "10": 0,
    "11": 0,
    "12": 0,
    "13": 0,
    "14": 0,
    "15": 0,
    "16": 0,
    "17": 0,
    "18": 0,
    "19": 0,
    "20": 0,
    "21": 0,
    "22": 0,
    "23": 0,
    "24": 0,
    "25": 0,
    "26": 0,
    "27": 0,
    "28": 0,
    "29": 0,
    "30": 0,
    "31": 0,
    "32": 0,
    "33": 0,
    "34": 0,
    "35": 0,
    "36": 0,
    "37": 0,
    "38": 0,
    "39": 0,
    "40": 0,
    "41": 0,
    "42": 0,
    "43": 0,
    "44": 7325,
    "45": 7325,
    "46": 7325,
    "47": 7325,
    "48": 7325,
    "49": 7325,
    "50": 7325,
    "51": 7325,
    "52": 7325,
    "53": 7325,
    "54": 7325,
    "55": 7325,
    "56": 7325,
    "57": 7325,
    "58": 7325,
    "59": 7325,
    "60": 7325,
    "61": 7325,
    "62": 7325,
    "63": 7325,
    "64": 7325,
    "65": 7325,
    "66": 7325,
    "67": 7325,
    "68": 7325,
    "69": 7325,
    "70": 7325,
    "71": 7325,
    "72": 7325,
    "73": 7325,
    "74": 7325,
    "75": 7325,
    "76": 7325,
    "77": 7325,
    "78": 7325,
    "79": 7325,
    "80": 7325,
    "81": 7325,
    "82": 7325,
    "83": 7325,
    "84": 7325,
    "85": 7325,
    "86": 7325
  }
}

In [47]:
df = pd.DataFrame.from_dict(js)

In [48]:
columns = {'0':'ID', '1':'search_input', '2':'postcode','3':'count_search', '4':'max_roof_id_number', '5':'max_roof_area', '6':'max_roof_number_panels', '7':'total_count_roofs', '8':'total_count_panels'}

In [49]:
df.rename(columns=columns, inplace=True)

In [50]:
df.head()

,ID,search_input,postcode,count_search,max_roof_id_number,max_roof_area,max_roof_number_panels,total_count_roofs,total_count_panels
0,None,SE23 3YL,SE23 3YL,45,0,0,0,0,0
1,None,G3 xxx,G3 xxx,1001,0,0,0,0,0
2,None,latt long,SE23 3YL,23,0,0,0,0,0
3,None,latt long,empty,1,0,0,0,0,0
4,None,SE23 3YL,SE23 3YL,45,0,0,0,0,0

In [52]:
df.drop_duplicates(subset='postcode', keep='last', inplace=True)

In [56]:
df

,ID,search_input,postcode,count_search,max_roof_id_number,max_roof_area,max_roof_number_panels,total_count_roofs,total_count_panels
19,None,latt long,empty,1,0,0,0,0,0
42,None,G3 xxx,G3 xxx,1001,0,0,0,0,0
86,None,SE23 3YL,SE23 3YL,68,722,17,5,723,7325

In [57]:

for index, row in df.iterrows():
    print('index ', index)
    print('row ', row['search_input'])
    
    all_data_dict[row['postcode']] = {"ID": row['ID'] , 
                                      "count":row['count_search'] ,
                                      "max_roof_id_number": row['max_roof_id_number'],
                                      "max_roof_area":row['max_roof_area'],
                                      "max_roof_number_panels": row['max_roof_number_panels'],
                                      "total_count_roofs": row['total_count_roofs'],
                                      "total_count_panels": row['total_count_panels']}

index  19
row  latt long
index  42
row  G3 xxx
index  86
row  SE23 3YL

In [58]:
all_data_dict

{'empty': {'ID': None,
  'count': 1,
  'max_roof_id_number': 0,
  'max_roof_area': 0,
  'max_roof_number_panels': 0,
  'total_count_roofs': 0,
  'total_count_panels': 0},
 'G3 xxx': {'ID': None,
  'count': 1001,
  'max_roof_id_number': 0,
  'max_roof_area': 0,
  'max_roof_number_panels': 0,
  'total_count_roofs': 0,
  'total_count_panels': 0},
 'SE23 3YL': {'ID': None,
  'count': 68,
  'max_roof_id_number': 722,
  'max_roof_area': 17,
  'max_roof_number_panels': 5,
  'total_count_roofs': 723,
  'total_count_panels': 7325}}

In [59]:
j = {
  "0": {
    "0": null,
    "1": null,
    "2": null,
    "3": null,
    "4": null,
    "5": null,
    "6": null,
    "7": null,
    "8": null,
    "9": null,
    "10": null,
    "11": null,
    "12": null,
    "13": null,
    "14": null,
    "15": null,
    "16": null,
    "17": null,
    "18": null,
    "19": null,
    "20": null,
    "21": null,
    "22": null,
    "23": null,
    "24": null,
    "25": null,
    "26": null,
    "27": null,
    "28": null,
    "29": null,
    "30": null,
    "31": null,
    "32": null,
    "33": null,
    "34": null,
    "35": null,
    "36": null,
    "37": null,
    "38": null,
    "39": null,
    "40": null,
    "41": null,
    "42": null,
    "43": null,
    "44": null,
    "45": null,
    "46": null,
    "47": null,
    "48": null,
    "49": null,
    "50": null,
    "51": null,
    "52": null,
    "53": null,
    "54": null,
    "55": null,
    "56": null,
    "57": null,
    "58": null,
    "59": null,
    "60": null,
    "61": null,
    "62": null,
    "63": null,
    "64": null,
    "65": null,
    "66": null,
    "67": null,
    "68": null
  },
  "1": {
    "0": "SE23 3YL",
    "1": "latt long",
    "2": "SE23 3YL",
    "3": "latt long",
    "4": "SE23 3YL",
    "5": "latt long",
    "6": "SE23 3YL",
    "7": "latt long",
    "8": "SE23 3YL",
    "9": "latt long",
    "10": "SE23 3YL",
    "11": "latt long",
    "12": "SE23 3YL",
    "13": "latt long",
    "14": "SE23 3YL",
    "15": "latt long",
    "16": "SE23 3YL",
    "17": "latt long",
    "18": "SE23 3YL",
    "19": "latt long",
    "20": "SE23 3YL",
    "21": "latt long",
    "22": "SE23 3YL",
    "23": "latt long",
    "24": "SE23 3YL",
    "25": "latt long",
    "26": "SE23 3YL",
    "27": "SE23 3YL",
    "28": "SE23 3YL",
    "29": "SE23 3YL",
    "30": "SE23 3YL",
    "31": "SE23 3YL",
    "32": "SE23 3YL",
    "33": "SE23 3YL",
    "34": "SE23 3YL",
    "35": "SE23 3YL",
    "36": "SE23 3YL",
    "37": "SE23 3YL",
    "38": "SE23 3YL",
    "39": "SE23 3YL",
    "40": "SE23 3YL",
    "41": "SE23 3YL",
    "42": "SE23 3YL",
    "43": "SE23 3YL",
    "44": "SE23 3YL",
    "45": "SE23 3YL",
    "46": "SE23 3YL",
    "47": "SE23 3YL",
    "48": "SE23 3YL",
    "49": "SE23 3YL",
    "50": "SE23 3YL",
    "51": "SE23 3YL",
    "52": "SE23 3YL",
    "53": "SE23 3YL",
    "54": "SE23 3YL",
    "55": "SE23 3YL",
    "56": "SE23 3YL",
    "57": "SE23 3YL",
    "58": "SE23 3YL",
    "59": "SE23 3YL",
    "60": "SE23 3YL",
    "61": "SE23 3YL",
    "62": "SE23 3YL",
    "63": "SE23 3YL",
    "64": "SE23 3YL",
    "65": "SE23 3YL",
    "66": "SE23 3YL",
    "67": "SE23 3YL",
    "68": "SE23 3YL"
  },
  "2": {
    "0": "SE23 3YL",
    "1": "SE23 3YL",
    "2": "SE23 3YL",
    "3": "SE23 3YL",
    "4": "SE23 3YL",
    "5": "SE23 3YL",
    "6": "SE23 3YL",
    "7": "SE23 3YL",
    "8": "SE23 3YL",
    "9": "SE23 3YL",
    "10": "SE23 3YL",
    "11": "SE23 3YL",
    "12": "SE23 3YL",
    "13": "SE23 3YL",
    "14": "SE23 3YL",
    "15": "SE23 3YL",
    "16": "SE23 3YL",
    "17": "SE23 3YL",
    "18": "SE23 3YL",
    "19": "SE23 3YL",
    "20": "SE23 3YL",
    "21": "SE23 3YL",
    "22": "SE23 3YL",
    "23": "SE23 3YL",
    "24": "SE23 3YL",
    "25": "SE23 3YL",
    "26": "SE23 3YL",
    "27": "SE23 3YL",
    "28": "SE23 3YL",
    "29": "SE23 3YL",
    "30": "SE23 3YL",
    "31": "SE23 3YL",
    "32": "SE23 3YL",
    "33": "SE23 3YL",
    "34": "SE23 3YL",
    "35": "SE23 3YL",
    "36": "SE23 3YL",
    "37": "SE23 3YL",
    "38": "SE23 3YL",
    "39": "SE23 3YL",
    "40": "SE23 3YL",
    "41": "SE23 3YL",
    "42": "SE23 3YL",
    "43": "SE23 3YL",
    "44": "SE23 3YL",
    "45": "SE23 3YL",
    "46": "SE23 3YL",
    "47": "SE23 3YL",
    "48": "SE23 3YL",
    "49": "SE23 3YL",
    "50": "SE23 3YL",
    "51": "SE23 3YL",
    "52": "SE23 3YL",
    "53": "SE23 3YL",
    "54": "SE23 3YL",
    "55": "SE23 3YL",
    "56": "SE23 3YL",
    "57": "SE23 3YL",
    "58": "SE23 3YL",
    "59": "SE23 3YL",
    "60": "SE23 3YL",
    "61": "SE23 3YL",
    "62": "SE23 3YL",
    "63": "SE23 3YL",
    "64": "SE23 3YL",
    "65": "SE23 3YL",
    "66": "SE23 3YL",
    "67": "SE23 3YL",
    "68": "SE23 3YL"
  },
  "3": {
    "0": 45,
    "1": 23,
    "2": 45,
    "3": 23,
    "4": 45,
    "5": 23,
    "6": 45,
    "7": 23,
    "8": 45,
    "9": 23,
    "10": 45,
    "11": 23,
    "12": 45,
    "13": 23,
    "14": 45,
    "15": 23,
    "16": 45,
    "17": 23,
    "18": 45,
    "19": 23,
    "20": 45,
    "21": 23,
    "22": 45,
    "23": 23,
    "24": 45,
    "25": 23,
    "26": 1,
    "27": 1,
    "28": 1,
    "29": 1,
    "30": 1,
    "31": 1,
    "32": 1,
    "33": 3,
    "34": 1,
    "35": 1,
    "36": 1,
    "37": 1,
    "38": 1,
    "39": 1,
    "40": 1,
    "41": 1,
    "42": 1,
    "43": 1,
    "44": 1,
    "45": 1,
    "46": 1,
    "47": 1,
    "48": 1,
    "49": 1,
    "50": 1,
    "51": 1,
    "52": 1,
    "53": 1,
    "54": 1,
    "55": 1,
    "56": 1,
    "57": 1,
    "58": 1,
    "59": 1,
    "60": 1,
    "61": 1,
    "62": 1,
    "63": 1,
    "64": 64,
    "65": 1,
    "66": 66,
    "67": 1,
    "68": 68
  },
  "4": {
    "0": 0,
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": 0,
    "8": 0,
    "9": 0,
    "10": 0,
    "11": 0,
    "12": 0,
    "13": 0,
    "14": 0,
    "15": 0,
    "16": 0,
    "17": 0,
    "18": 0,
    "19": 0,
    "20": 0,
    "21": 0,
    "22": 0,
    "23": 0,
    "24": 0,
    "25": 0,
    "26": 722,
    "27": 722,
    "28": 722,
    "29": 722,
    "30": 722,
    "31": 722,
    "32": 722,
    "33": 722,
    "34": 722,
    "35": 722,
    "36": 722,
    "37": 722,
    "38": 722,
    "39": 722,
    "40": 722,
    "41": 722,
    "42": 722,
    "43": 722,
    "44": 722,
    "45": 722,
    "46": 722,
    "47": 722,
    "48": 722,
    "49": 722,
    "50": 722,
    "51": 722,
    "52": 722,
    "53": 722,
    "54": 722,
    "55": 722,
    "56": 722,
    "57": 722,
    "58": 722,
    "59": 722,
    "60": 722,
    "61": 722,
    "62": 722,
    "63": 722,
    "64": 722,
    "65": 722,
    "66": 722,
    "67": 722,
    "68": 722
  },
  "5": {
    "0": 0,
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": 0,
    "8": 0,
    "9": 0,
    "10": 0,
    "11": 0,
    "12": 0,
    "13": 0,
    "14": 0,
    "15": 0,
    "16": 0,
    "17": 0,
    "18": 0,
    "19": 0,
    "20": 0,
    "21": 0,
    "22": 0,
    "23": 0,
    "24": 0,
    "25": 0,
    "26": 17,
    "27": 17,
    "28": 17,
    "29": 17,
    "30": 17,
    "31": 17,
    "32": 17,
    "33": 17,
    "34": 17,
    "35": 17,
    "36": 17,
    "37": 17,
    "38": 17,
    "39": 17,
    "40": 17,
    "41": 17,
    "42": 17,
    "43": 17,
    "44": 17,
    "45": 17,
    "46": 17,
    "47": 17,
    "48": 17,
    "49": 17,
    "50": 17,
    "51": 17,
    "52": 17,
    "53": 17,
    "54": 17,
    "55": 17,
    "56": 17,
    "57": 17,
    "58": 17,
    "59": 17,
    "60": 17,
    "61": 17,
    "62": 17,
    "63": 17,
    "64": 17,
    "65": 17,
    "66": 17,
    "67": 17,
    "68": 17
  },
  "6": {
    "0": 0,
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": 0,
    "8": 0,
    "9": 0,
    "10": 0,
    "11": 0,
    "12": 0,
    "13": 0,
    "14": 0,
    "15": 0,
    "16": 0,
    "17": 0,
    "18": 0,
    "19": 0,
    "20": 0,
    "21": 0,
    "22": 0,
    "23": 0,
    "24": 0,
    "25": 0,
    "26": 5,
    "27": 5,
    "28": 5,
    "29": 5,
    "30": 5,
    "31": 5,
    "32": 5,
    "33": 5,
    "34": 5,
    "35": 5,
    "36": 5,
    "37": 5,
    "38": 5,
    "39": 5,
    "40": 5,
    "41": 5,
    "42": 5,
    "43": 5,
    "44": 5,
    "45": 5,
    "46": 5,
    "47": 5,
    "48": 5,
    "49": 5,
    "50": 5,
    "51": 5,
    "52": 5,
    "53": 5,
    "54": 5,
    "55": 5,
    "56": 5,
    "57": 5,
    "58": 5,
    "59": 5,
    "60": 5,
    "61": 5,
    "62": 5,
    "63": 5,
    "64": 5,
    "65": 5,
    "66": 5,
    "67": 5,
    "68": 5
  },
  "7": {
    "0": 0,
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": 0,
    "8": 0,
    "9": 0,
    "10": 0,
    "11": 0,
    "12": 0,
    "13": 0,
    "14": 0,
    "15": 0,
    "16": 0,
    "17": 0,
    "18": 0,
    "19": 0,
    "20": 0,
    "21": 0,
    "22": 0,
    "23": 0,
    "24": 0,
    "25": 0,
    "26": 723,
    "27": 723,
    "28": 723,
    "29": 723,
    "30": 723,
    "31": 723,
    "32": 723,
    "33": 723,
    "34": 723,
    "35": 723,
    "36": 723,
    "37": 723,
    "38": 723,
    "39": 723,
    "40": 723,
    "41": 723,
    "42": 723,
    "43": 723,
    "44": 723,
    "45": 723,
    "46": 723,
    "47": 723,
    "48": 723,
    "49": 723,
    "50": 723,
    "51": 723,
    "52": 723,
    "53": 723,
    "54": 723,
    "55": 723,
    "56": 723,
    "57": 723,
    "58": 723,
    "59": 723,
    "60": 723,
    "61": 723,
    "62": 723,
    "63": 723,
    "64": 723,
    "65": 723,
    "66": 723,
    "67": 723,
    "68": 723
  },
  "8": {
    "0": 0,
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": 0,
    "8": 0,
    "9": 0,
    "10": 0,
    "11": 0,
    "12": 0,
    "13": 0,
    "14": 0,
    "15": 0,
    "16": 0,
    "17": 0,
    "18": 0,
    "19": 0,
    "20": 0,
    "21": 0,
    "22": 0,
    "23": 0,
    "24": 0,
    "25": 0,
    "26": 7325,
    "27": 7325,
    "28": 7325,
    "29": 7325,
    "30": 7325,
    "31": 7325,
    "32": 7325,
    "33": 7325,
    "34": 7325,
    "35": 7325,
    "36": 7325,
    "37": 7325,
    "38": 7325,
    "39": 7325,
    "40": 7325,
    "41": 7325,
    "42": 7325,
    "43": 7325,
    "44": 7325,
    "45": 7325,
    "46": 7325,
    "47": 7325,
    "48": 7325,
    "49": 7325,
    "50": 7325,
    "51": 7325,
    "52": 7325,
    "53": 7325,
    "54": 7325,
    "55": 7325,
    "56": 7325,
    "57": 7325,
    "58": 7325,
    "59": 7325,
    "60": 7325,
    "61": 7325,
    "62": 7325,
    "63": 7325,
    "64": 7325,
    "65": 7325,
    "66": 7325,
    "67": 7325,
    "68": 7325
  }
}

In [60]:
df = pd.DataFrame.from_dict(j)

In [61]:
df

       0          1         2   3    4   5  6    7     8
0   None   SE23 3YL  SE23 3YL  45    0   0  0    0     0
1   None  latt long  SE23 3YL  23    0   0  0    0     0
2   None   SE23 3YL  SE23 3YL  45    0   0  0    0     0
3   None  latt long  SE23 3YL  23    0   0  0    0     0
4   None   SE23 3YL  SE23 3YL  45    0   0  0    0     0
..   ...        ...       ...  ..  ...  .. ..  ...   ...
64  None   SE23 3YL  SE23 3YL  64  722  17  5  723  7325
65  None   SE23 3YL  SE23 3YL   1  722  17  5  723  7325
66  None   SE23 3YL  SE23 3YL  66  722  17  5  723  7325
67  None   SE23 3YL  SE23 3YL   1  722  17  5  723  7325
68  None   SE23 3YL  SE23 3YL  68  722  17  5  723  7325

[69 rows x 9 columns]

In [62]:
df.rename(columns=columns, inplace=True)
df.drop_duplicates(subset='postcode', keep='last', inplace=True)

In [63]:
df

,ID,search_input,postcode,count_search,max_roof_id_number,max_roof_area,max_roof_number_panels,total_count_roofs,total_count_panels
68,None,SE23 3YL,SE23 3YL,68,722,17,5,723,7325

In [64]:
one_postcode = {}
for index, row in df.iterrows():
    print('index ', index)
    print('row ', row['search_input'])
    
    one_postcode[row['postcode']] = {"ID": row['ID'] , 
                                      "count":row['count_search'] ,
                                      "max_roof_id_number": row['max_roof_id_number'],
                                      "max_roof_area":row['max_roof_area'],
                                      "max_roof_number_panels": row['max_roof_number_panels'],
                                      "total_count_roofs": row['total_count_roofs'],
                                      "total_count_panels": row['total_count_panels']}

index  68
row  SE23 3YL

In [65]:
one_postcode

{'SE23 3YL': {'ID': None,
  'count': 68,
  'max_roof_id_number': 722,
  'max_roof_area': 17,
  'max_roof_number_panels': 5,
  'total_count_roofs': 723,
  'total_count_panels': 7325}}